"""
Image Generation MCP Tools

Corresponds to: POST /api/generate/, GET /api/generate/queue, POST /api/generate/custom
Supports character and style semantic mapping (character_style).
Supports custom workflows that can be dynamically generated by AI based on user descriptions.
"""
import json

from mcp_server.character_style import resolve_to_prompt
from mcp_server.config import get_mcp_settings
# parse_description 僅供下方已停用的 *_from_description 工具使用，連同一併註解。
# from mcp_server.description_parser import parse_description
from mcp_server.server import _get_client, mcp


@mcp.tool()
def generate_image(
    prompt: str = "1girl, solo",
    character: str | None = None,
    style: str | None = None,
    checkpoint: str | None = None,
    lora: str | None = None,
    template: str | None = None,
    negative_prompt: str | None = None,
    seed: int | None = None,
    steps: int | None = None,
    cfg: float | None = None,
    width: int | None = None,
    height: int | None = None,
    batch_size: int | None = None,
    sampler_name: str | None = None,
    scheduler: str | None = None,
    lora_strength: float | None = None,
    loras: list[dict] | None = None,
    denoise: float | None = None,
    diffusion_model: str | None = None,
    text_encoder: str | None = None,
    vae: str | None = None,
) -> str:
    """Trigger image generation. Accepts character and style in natural language or a direct prompt. Supports full parameter control: sampler_name, scheduler, lora_strength, denoise, width/height, etc. batch_size allows generating multiple images at once (1-8). template selects the workflow template (e.g. "anima" for the Anima diffusion-model family); omit it to auto-pick default / default_lora based on lora. diffusion_model / text_encoder / vae are components for diffusion-model families (e.g. Anima), injected into UNETLoader / CLIPLoader / VAELoader; include them only when needed (a composed style preset payload may already provide them). Call list_workflow_templates to see available names. loras is an ordered list of {name, strength_model, strength_clip?} for multi-LoRA workflows — mapped to the workflow's LoraLoader nodes in order and taking precedence over the single lora; use it for templates whose capability includes multi_lora. Returns job_id or an error message."""
    try:
        client = _get_client()
        final_prompt = prompt
        resolved_lora = lora

        if character or style:
            base = prompt if prompt else "1girl, solo"
            final_prompt, style_lora = resolve_to_prompt(
                character=character, style=style, base_prompt=base
            )
            if style_lora and not resolved_lora:
                resolved_lora = style_lora

        body: dict[str, object] = {"prompt": final_prompt}
        if checkpoint:
            body["checkpoint"] = checkpoint
        if template:
            body["template"] = template
        if resolved_lora:
            body["lora"] = resolved_lora
        if negative_prompt is not None:
            body["negative_prompt"] = negative_prompt
        if seed is not None:
            body["seed"] = seed
        if steps is not None:
            body["steps"] = steps
        if cfg is not None:
            body["cfg"] = cfg
        if batch_size is not None:
            if 1 <= batch_size <= 8:
                body["batch_size"] = batch_size
        else:
            body["batch_size"] = 1
        if width is not None:
            body["width"] = width
        if height is not None:
            body["height"] = height
        if sampler_name is not None:
            body["sampler_name"] = sampler_name
        if scheduler is not None:
            body["scheduler"] = scheduler
        if lora_strength is not None:
            body["lora_strength"] = lora_strength
        if loras is not None:
            body["loras"] = loras
        if denoise is not None:
            body["denoise"] = denoise
        if diffusion_model is not None:
            body["diffusion_model"] = diffusion_model
        if text_encoder is not None:
            body["text_encoder"] = text_encoder
        if vae is not None:
            body["vae"] = vae
        resp = client.post("generate/", json=body)
        job_id = resp.get("job_id", "unknown")
        status = resp.get("status", "queued")
        return json.dumps(
            {
                "ok": True,
                "tool": "generate_image",
                "job_id": job_id,
                "status": status,
                "submitted": body,
                "next": "call get_generation_status with this job_id",
            },
            ensure_ascii=False,
        )
    except Exception as e:
        return json.dumps(
            {
                "ok": False,
                "tool": "generate_image",
                "where": "backend",
                "error": str(e),
            },
            ensure_ascii=False,
        )


@mcp.tool()
def list_workflow_templates() -> str:
    """List available workflow template names. AI can select a template based on the user's description, then call get_workflow_template to retrieve the JSON."""
    try:
        client = _get_client()
        resp = client.get("generate/workflow-templates")
        templates = resp.get("templates", [])
        if not templates:
            return "目前無 workflow 模板"
        return "可用模板：" + ", ".join(templates)
    except Exception as e:
        return f"error: {e}"


@mcp.tool()
def get_workflow_template(template_name: str) -> str:
    """Get the full JSON for a specified workflow template. Returns a JSON string that can be passed as the workflow parameter to generate_image_custom_workflow."""
    try:
        client = _get_client()
        workflow = client.get(f"generate/workflow-templates/{template_name}")
        return json.dumps(workflow, ensure_ascii=False)
    except Exception as e:
        return f"error: {e}"


@mcp.tool()
def generate_image_custom_workflow(
    workflow: str,
    prompt: str = "1girl, solo",
    character: str | None = None,
    style: str | None = None,
    checkpoint: str | None = None,
    lora: str | None = None,
    negative_prompt: str | None = None,
    seed: int | None = None,
    steps: int | None = None,
    cfg: float | None = None,
    width: int | None = None,
    height: int | None = None,
    image: str | None = None,
    image_pose: str | None = None,
    mask: str | None = None,
    batch_size: int | None = None,
    sampler_name: str | None = None,
    scheduler: str | None = None,
    lora_strength: float | None = None,
    loras: list[dict] | None = None,
    denoise: float | None = None,
    diffusion_model: str | None = None,
    text_encoder: str | None = None,
    vae: str | None = None,
) -> str:
    """
    Trigger image generation using a custom workflow. AI should:
    1. Call list_workflow_templates to see available templates
    2. Call get_workflow_template(name) to retrieve the JSON
    3. Optionally modify the workflow JSON (e.g. adjust nodes or parameters)
    4. Pass it to this tool; workflow must be a JSON string; prompt/character/style will be applied to the workflow

    This is the most flexible generation tool: since the workflow JSON is a full computation
    graph, it can in principle cover any scenario — txt2img, img2img, ControlNet, inpaint,
    diffusion-model families like Anima.

    image: subject reference image for img2img, relative to gallery_dir (e.g. 2026-03-08/subject.png).
    The backend uploads it to ComfyUI and replaces the first LoadImage node's image input.

    mask: inpaint mask image, relative to gallery_dir. Use together with the "inpaint" workflow
    template (LoadImage subject + LoadImageMask + VAEEncodeForInpaint). The backend uploads it
    and replaces the LoadImageMask node's image input; it never collides with the subject image
    since they are distinct node types.

    image_pose: pose reference image, relative to gallery_dir (e.g. 2026-03-08/ComfyUI_xxx.png).
    The backend reads it from the gallery, uploads it to ComfyUI, and replaces the LoadImage node. Used for ControlNet pose, etc.

    diffusion_model / text_encoder / vae: components for diffusion-model families (e.g. Anima),
    injected into UNETLoader.unet_name / CLIPLoader.clip_name / VAELoader.vae_name respectively.

    Important: every parameter here is only applied when explicitly provided. Any value already
    present in the submitted workflow JSON (steps, cfg, seed, model filenames, etc.) is left as-is
    when the corresponding parameter is omitted — the workflow JSON is the source of truth. This
    means a workflow with a fixed/non-zero seed will reproduce deterministically unless you pass
    seed explicitly for variation, and hires-fix / multi-KSampler graphs keep each sampler's own
    steps/cfg.
    """
    try:
        client = _get_client()
        wf_obj = json.loads(workflow)
        final_prompt = prompt
        resolved_lora = lora
        if character or style:
            base = prompt if prompt else "1girl, solo"
            final_prompt, style_lora = resolve_to_prompt(
                character=character, style=style, base_prompt=base
            )
            if style_lora and not resolved_lora:
                resolved_lora = style_lora
        body = {
            "workflow": wf_obj,
            "prompt": final_prompt,
        }
        if checkpoint:
            body["checkpoint"] = checkpoint
        if resolved_lora:
            body["lora"] = resolved_lora
        if negative_prompt is not None:
            body["negative_prompt"] = negative_prompt
        if seed is not None:
            body["seed"] = seed
        if steps is not None:
            body["steps"] = steps
        if cfg is not None:
            body["cfg"] = cfg
        if width is not None:
            body["width"] = width
        if height is not None:
            body["height"] = height
        if image is not None:
            body["image"] = image
        if image_pose is not None:
            body["image_pose"] = image_pose
        if mask is not None:
            body["mask"] = mask
        if batch_size is not None:
            body["batch_size"] = batch_size
        if sampler_name is not None:
            body["sampler_name"] = sampler_name
        if scheduler is not None:
            body["scheduler"] = scheduler
        if lora_strength is not None:
            body["lora_strength"] = lora_strength
        if loras is not None:
            body["loras"] = loras
        if denoise is not None:
            body["denoise"] = denoise
        if diffusion_model is not None:
            body["diffusion_model"] = diffusion_model
        if text_encoder is not None:
            body["text_encoder"] = text_encoder
        if vae is not None:
            body["vae"] = vae
        resp = client.post("generate/custom", json=body)
        job_id = resp.get("job_id", "unknown")
        status = resp.get("status", "queued")
        return json.dumps(
            {
                "ok": True,
                "tool": "generate_image_custom_workflow",
                "job_id": job_id,
                "status": status,
                "next": "poll get_generation_status(job_id); if status=failed with node_errors, fix those nodes and resubmit; if it completes and this is a reusable new shape, consider save_workflow_template(job_id, ...) so future needs match it",
            },
            ensure_ascii=False,
        )
    except json.JSONDecodeError as e:
        return json.dumps(
            {"ok": False, "tool": "generate_image_custom_workflow", "error": f"workflow 必須為合法 JSON: {e}"},
            ensure_ascii=False,
        )
    except Exception as e:
        return json.dumps(
            {"ok": False, "tool": "generate_image_custom_workflow", "where": "backend", "error": str(e)},
            ensure_ascii=False,
        )


@mcp.tool()
def generate_video_custom_workflow(
    workflow: str,
    prompt: str = "1girl, solo",
    image: str | None = None,
    first_frame: str | None = None,
    last_frame: str | None = None,
    video_ref: str | None = None,
    negative_prompt: str | None = None,
    seed: int | None = None,
    steps: int | None = None,
    cfg: float | None = None,
    width: int | None = None,
    height: int | None = None,
    batch_size: int | None = None,
    sampler_name: str | None = None,
    scheduler: str | None = None,
    denoise: float | None = None,
    diffusion_model: str | None = None,
    text_encoder: str | None = None,
    vae: str | None = None,
) -> str:
    """Submit a supplied ComfyUI video workflow JSON through the normal generation queue. This MVP does not synthesize a video graph from prose; start from a known-good local workflow, optionally inject gallery-relative image/first_frame/last_frame/video_ref inputs, then poll get_generation_status."""
    try:
        client = _get_client()
        wf_obj = json.loads(workflow)
        body: dict[str, object] = {
            "workflow": wf_obj,
            "prompt": prompt,
        }
        optional_values = {
            "image": image,
            "first_frame": first_frame,
            "last_frame": last_frame,
            "video_ref": video_ref,
            "negative_prompt": negative_prompt,
            "seed": seed,
            "steps": steps,
            "cfg": cfg,
            "width": width,
            "height": height,
            "batch_size": batch_size,
            "sampler_name": sampler_name,
            "scheduler": scheduler,
            "denoise": denoise,
            "diffusion_model": diffusion_model,
            "text_encoder": text_encoder,
            "vae": vae,
        }
        for key, value in optional_values.items():
            if value is not None:
                body[key] = value
        resp = client.post("generate/video/custom", json=body)
        job_id = resp.get("job_id", "unknown")
        status = resp.get("status", "queued")
        return json.dumps(
            {
                "ok": True,
                "tool": "generate_video_custom_workflow",
                "job_id": job_id,
                "status": status,
                "next": "poll get_generation_status(job_id); on completion use artifacts[] with get_gallery_artifact; if failed with node_errors, inspect schemas and resubmit a corrected workflow",
            },
            ensure_ascii=False,
        )
    except json.JSONDecodeError as e:
        return json.dumps(
            {"ok": False, "tool": "generate_video_custom_workflow", "error": f"workflow 必須為合法 JSON: {e}"},
            ensure_ascii=False,
        )
    except Exception as e:
        return json.dumps(
            {"ok": False, "tool": "generate_video_custom_workflow", "where": "backend", "error": str(e)},
            ensure_ascii=False,
        )


# ---------------------------------------------------------------------------
# 已停用：generate_image_from_description / suggest_workflow_from_description
#
# 原因：這兩個工具的核心是 description_parser.parse_description()，一個寫死的
# 關鍵字／正則解析器（角色與風格只比對字面別名、中文轉英文僅 4 個硬編字、解析度
# 只認 512/768/1024、template 只在出現 "lora" 字樣時切換）。它本質上是給「不會
# 推理的規則型 client」用的 NLP fallback。
#
# 在由 LLM agent 接管的 MCP 生圖流程中，agent 本來就能把自然語言直接拆成結構化
# 參數，且遠比 regex 準確（同義詞、英文、複雜場景都能處理）。因此：
#   - 想一句話生圖 → agent 自行解析後直接呼叫 generate_image(prompt=, character=,
#     style=, width=, ...)
#   - 想生圖前預覽 → 改用 resolve_character_style_prompt(...)
#   - 想走風格食譜 → compose_style_preset(...) → generate_image(...)
#
# 保留原始碼（註解形式）以便日後若需支援非 agent client 時還原；底層的
# character/style 語意映射（resolve_to_prompt）不受影響，仍由 generate_image 使用。
# ---------------------------------------------------------------------------
# @mcp.tool()
# def generate_image_from_description(description: str) -> str:
#     """
#     Generate an image from a natural language description using preset templates.
#     Parses character, style, resolution, and extra prompt, then selects a template and submits.
#     Example: "Miku in a kimono, anime style, 1024"
#     If the description requires ControlNet, img2img, or other features not in the preset templates, the AI should compose a workflow and call generate_image_custom_workflow instead.
#     """
#     try:
#         parsed = parse_description(description)
#         client = _get_client()
#         workflow = client.get(f"generate/workflow-templates/{parsed.template}")
#         final_prompt, resolved_lora = resolve_to_prompt(
#             character=parsed.character,
#             style=parsed.style,
#             base_prompt="1girl, solo",
#         )
#         if parsed.extra_prompt:
#             final_prompt = f"{final_prompt}, {parsed.extra_prompt}"
#         body = {"workflow": workflow, "prompt": final_prompt}
#         if resolved_lora:
#             body["lora"] = resolved_lora
#         if parsed.width is not None:
#             body["width"] = parsed.width
#         if parsed.height is not None:
#             body["height"] = parsed.height
#         resp = client.post("generate/custom", json=body)
#         job_id = resp.get("job_id", "unknown")
#         status = resp.get("status", "queued")
#         summary = f"template={parsed.template}, character={parsed.character}, style={parsed.style}"
#         if parsed.width:
#             summary += f", {parsed.width}x{parsed.height}"
#         return f"已加入生圖佇列：job_id={job_id}, status={status}\n{summary}"
#     except Exception as e:
#         return f"error: {e}"
#
#
# @mcp.tool()
# def suggest_workflow_from_description(description: str) -> str:
#     """
#     Parse the description only, without returning a workflow JSON. Use for previewing or letting the AI understand which parameters would be selected.
#     """
#     try:
#         parsed = parse_description(description)
#         _, resolved_lora = resolve_to_prompt(
#             character=parsed.character,
#             style=parsed.style,
#             base_prompt="1girl, solo",
#         )
#         lines = [
#             f"character: {parsed.character or '(未辨識)'}",
#             f"style: {parsed.style or '(未辨識)'}",
#             f"extra_prompt: {parsed.extra_prompt or '(無)'}",
#             f"template: {parsed.template}",
#             f"resolution: {parsed.width}x{parsed.height}" if parsed.width else "resolution: (預設)",
#         ]
#         if resolved_lora:
#             lines.append(f"lora: {resolved_lora}")
#         return "\n".join(lines)
#     except Exception as e:
#         return f"error: {e}"


@mcp.tool()
def generate_queue_status() -> str:
    """Get image generation queue status (running and pending jobs)."""
    try:
        client = _get_client()
        resp = client.get("generate/queue")
        running = resp.get("queue_running", [])
        pending = resp.get("queue_pending", [])
        lines = [
            f"執行中：{len(running)} 筆",
            *[f"  - {r.get('job_id', '?')}: {r.get('status', '?')}" for r in running],
            f"等候中：{len(pending)} 筆",
            *[f"  - {p.get('job_id', '?')}: {p.get('status', '?')}" for p in pending],
        ]
        return "\n".join(lines) if lines else "佇列為空"
    except Exception as e:
        return f"error: {e}"


@mcp.tool()
def get_generation_status(job_id: str) -> str:
    """Query generation job status, returns agent-friendly JSON. Completed jobs include artifacts[]; image jobs keep image_id/image_path. Failed custom workflows return structured node_errors or recording_error."""
    try:
        client = _get_client()
        resp = client.get(f"generate/job/{job_id}")
        status = resp.get("status", "unknown")
        if status == "completed":
            artifacts = resp.get("artifacts", [])
            has_non_image_artifact = any(
                artifact.get("artifact_type") != "image"
                for artifact in artifacts
                if isinstance(artifact, dict)
            )
            next_step = (
                "call get_gallery_artifact with an artifact id from artifacts[], then free_comfyui_memory"
                if has_non_image_artifact
                else "call get_gallery_image with image_id, then free_comfyui_memory"
            )
            return json.dumps(
                {
                    "ok": True,
                    "tool": "get_generation_status",
                    "job_id": job_id,
                    "status": "completed",
                    "image_id": resp.get("image_id"),
                    "image_path": resp.get("image_path", ""),
                    "artifacts": artifacts,
                    "next": next_step,
                },
                ensure_ascii=False,
            )
        elif status == "failed":
            node_errors = resp.get("node_errors", [])
            return json.dumps(
                {
                    "ok": False,
                    "tool": "get_generation_status",
                    "where": "comfyui",
                    "job_id": job_id,
                    "status": "failed",
                    "error": resp.get("error"),
                    "node_errors": node_errors,
                    "recording_error": resp.get("recording_error"),
                    "next": (
                        "fix the offending nodes (check names/inputs via get_node_schema) and resubmit generate_image_custom_workflow"
                        if node_errors
                        else "generation failed; inspect error and resubmit"
                    ),
                },
                ensure_ascii=False,
            )
        elif status in ("queued", "running"):
            return json.dumps(
                {
                    "ok": True,
                    "tool": "get_generation_status",
                    "job_id": job_id,
                    "status": status,
                    "prompt_id": resp.get("prompt_id"),
                    "next": "wait, then call get_generation_status again",
                },
                ensure_ascii=False,
            )
        else:
            return json.dumps(
                {
                    "ok": False,
                    "tool": "get_generation_status",
                    "where": "backend",
                    "job_id": job_id,
                    "error": f"Job not found or unexpected status: {status}",
                },
                ensure_ascii=False,
            )
    except Exception as e:
        return json.dumps(
            {
                "ok": False,
                "tool": "get_generation_status",
                "where": "backend",
                "job_id": job_id,
                "error": str(e),
            },
            ensure_ascii=False,
        )


@mcp.tool()
def cancel_job(job_id: str) -> str:
    """Cancel an image generation job that has not yet started (pending status). Running jobs cannot be cancelled."""
    try:
        client = _get_client()
        resp = client.delete(f"generate/queue/{job_id}")
        return resp.get("message", "已取消")
    except Exception as e:
        return f"error: {e}"


@mcp.tool()
def list_available_resources() -> str:
    """List available checkpoints, LoRAs, diffusion models, text encoders, VAEs, optional video resources, and workflow templates, returns agent-friendly JSON."""
    try:
        client = _get_client()
        resp = client.get("generate/available-resources")
        checkpoints = resp.get("checkpoints", [])
        loras = resp.get("loras", [])
        diffusion_models = resp.get("diffusion_models", [])
        text_encoders = resp.get("text_encoders", [])
        vaes = resp.get("vaes", [])
        video_models = resp.get("video_models", [])
        video_loras = resp.get("video_loras", [])
        video_inputs = resp.get("video_inputs", [])
        workflows = resp.get("workflows", [])
        default_checkpoint = resp.get("default_checkpoint")
        next_step = (
            "choose a checkpoint, then call generate_image"
            if checkpoints
            else "no checkpoints available; do not call generate_image until backend resources are fixed"
        )
        return json.dumps(
            {
                "ok": True,
                "tool": "list_available_resources",
                "backend_base_url": get_mcp_settings().backend_api_url,
                "checkpoints": checkpoints,
                "loras": loras,
                "diffusion_models": diffusion_models,
                "text_encoders": text_encoders,
                "vaes": vaes,
                "video_models": video_models,
                "video_loras": video_loras,
                "video_inputs": video_inputs,
                "workflows": workflows,
                "default_checkpoint": default_checkpoint,
                "next": next_step,
            },
            ensure_ascii=False,
        )
    except Exception as e:
        return json.dumps(
            {
                "ok": False,
                "tool": "list_available_resources",
                "where": "backend",
                "error": str(e),
            },
            ensure_ascii=False,
        )

